### ISSUE TITLE
HTMLDocument.registerElement is deprecated.

### ISSUE THREAD

**Issue by tarunsriram** [atom-community/buildium#22] opened 2024-09-09 21:19 UTC
Use `customElements.define` instead of `document.registerElement` see https://javascript.info/custom-elements
```
HTMLDocument.registerElement (file:///Applications/Pulsar.app/Contents/Resources/app.asar/static/index.js:100:12)
registerElement (/Users/tsriram/.pulsar/packages/script/node_modules/space-pen/lib/space-pen.js:66:88)
Builder.openTag (/Users/tsriram/.pulsar/packages/script/node_modules/space-pen/lib/space-pen.js:297:27)
Builder.tag (/Users/tsriram/.pulsar/packages/script/node_modules/space-pen/lib/space-pen.js:274:12)
Function.div (/Users/tsriram/.pulsar/packages/script/node_modules/space-pen/lib/space-pen.js:83:49)
Function.value (/Users/tsriram/.pulsar/packages/buildium/lib/buildium.js:1:37843)
```

**Comment by idleberg** [comment] 2024-09-11 08:37
Duplicate of https://github.com/atom-community/buildium/issues/14

**Closed as completed by idleberg** 2024-09-11 08:37 UTC
