### ISSUE TITLE
HTMLDocument.registerElement is deprecated.

### ISSUE THREAD

**Issue by rizwansammo** [atom-community/buildium#19] opened 2024-07-09 18:44 UTC
Use `customElements.define` instead of `document.registerElement` see https://javascript.info/custom-elements
```
HTMLDocument.registerElement (file:///C:/Users/Rizwan/AppData/Local/Programs/Pulsar/resources/app.asar/static/index.js:100:12)
registerElement (C:\Users\Rizwan\.pulsar\packages\buildium\node_modules\space-pen\lib\space-pen.js:66:88)
Builder.openTag (C:\Users\Rizwan\.pulsar\packages\buildium\node_modules\space-pen\lib\space-pen.js:297:27)
Builder.tag (C:\Users\Rizwan\.pulsar\packages\buildium\node_modules\space-pen\lib\space-pen.js:274:12)
Function.div (C:\Users\Rizwan\.pulsar\packages\buildium\node_modules\space-pen\lib\space-pen.js:83:49)
Function.value (C:\Users\Rizwan\.pulsar\packages\buildium\lib\buildium.js:1:37843)
```

**Comment by idleberg** [comment] 2024-07-10 05:11
Duplicate of https://github.com/atom-community/buildium/issues/14

**Closed as completed** 2024-07-10 05:16 UTC
